### ISSUE TITLE
Question : best practise to catch error (token invalid) 

### ISSUE THREAD

**Issue by andreas83** [reststate/reststate-vuex#144]
From time to time my token get`s invalid, need to renewed, where is the best place to catch the error?

**Comment by CodingItWrong** [comment]
I can think of two ways two approach this:

1. Write a function that wraps any of your Reststate-Vuex actions. That function will execute your action, check for an error, and if the auth error occurs, will re-auth and then re-execute the action. The downside of this approach is you'd have to remember to wrap every action in that function.

2. Instead of passing an Axios instance to the client, pass in a custom HTTP client object that defines `get`, `post`, `patch`, and `delete` methods. In each of those methods, you can pass the request along to Axios. Then, if an auth error occurs, you re-auth and re-send the request to Axios. This is the approach I think you might have the best luck with.

If it works out and you'd be willing to contribute your code to the guides, let me know—I'd be happy to post it as an example to others!

**Comment by andreas83** [comment]
i will go for the second approach, also i would love to contribute my implementation.

**Comment by andreas83** [comment]
Okay found a very nice solution for this.
You don't have to wrap any function neither have to extend the axios instance since Axiossupports response interceptors.


```
const api = axios.create({
  baseURL: document.head.querySelector('meta[name="api-base-url"]').content,
  headers: {
    'Content-Type': 'application/vnd.api+json',
    'Accept': 'application/vnd.api+json',
    'Authorization': `Bearer ${token}`,
  },
});


// Add a response interceptor
api.interceptors.response.use(function (response) {
    return response;
  }, function (error) {
    console.log(error);
    //here you can handle the token invalid error 
   return Promise.reject(error);
});


export const store = new Vuex.Store({
  state: {
    status: '',
    token: localStorage.getItem('token') || ''
  },
  modules: {
      ...mapResourceModules({
      names: [
        'dashboardItems'
      ],
      httpClient: api
    }),
  },
  mutations: {},
  actions: {}
})
```

**Comment by CodingItWrong** [comment]
Thanks for the info; hopefully this issue will help folks in the future with this question.
