### ISSUE TITLE
the byId getter doesn't work. 

### ISSUE THREAD

**Issue by andreas83** [reststate/reststate-vuex#15]
For me it looks like the **byId** getter does not work as expected. 
the loadById action seems to work fine, but the getter byId only returns a function not the result:

`({ id }) => state.records.find(r => r.id === id)`

**Comment by CodingItWrong** [comment]
Thanks for looking into #13 yourself, I'll review that and talk more later!

But to get you an answer on this point, notice in the docs that you call that getter as a function and pass the ID you're looking up: https://vuex.reststate.org/reading-data.html#loadbyid-action-byid-getter

```
const widget = this.$store.getters['widgets/byId']({ id: 42 });
console.log(widget);
```

Vuex calls this method-style access, and it's not quite as common, but it's a thing that's done: https://vuex.vuejs.org/guide/getters.html#method-style-access

Closing because I _think_ this addresses it; please reopen if it gives you any more trouble.

**Comment by andreas83** [comment]
i'm still pretty sure that there is a bug 

```
            this.$store.dispatch('sensors/loadById', { id: 1 })
            .then(() => {
              const sensor = this.$store.getters['sensors/byId']({ id: 1 });
              console.log(sensor);
            });
```

results **undefined** but 

```
            const filter = {
              id: 1,
            };
            this.$store.dispatch('sensors/loadWhere', { filter })
              .then(() => {
                const sensor = this.$store.getters['sensors/where']({ filter });
                console.log(sensor);
            });
```
results the object

**Comment by CodingItWrong** [comment]
OK, I just tried the above in my own code and I may have found the problem. Try changing the ID 1 to a string, '1':

```
            this.$store.dispatch('sensors/loadById', { id: '1' })
            .then(() => {
              const sensor = this.$store.getters['sensors/byId']({ id: '1' });
              console.log(sensor);
            });
```

My example code where the ID is a number is wrong and I need to fix it. So I expect it'll fix your code.

JSON:API specifies that IDs must be strings, so that is probably what is being returned by your server. And the `byId` getter does a `===` check, so a returned string ID '1' will not be equal to a number 1.

(I don't think `loadById` cares if the ID is a string or number, because either way it gets turned into a string as part of the URL.)

Let me know if that fixes it!

**Comment by andreas83** [comment]
1. Above example works, this is quite painful in many ways but on the same page iam glad you found the reason. 
I would recommend to add some sort of parameter validation and error reporting.
or and in this specific case i would maybe just add a silent type conversion.... 

2. I found another small typo in your docu:
```
this.$store.dispatch('widgets/loadWhere', { filter });
  .then(() => {
```
the ; semicolon should not be here. 

3.  while the above example works, the following code still get stuck (properly for the same reason)

```
<template>
    <div>
            <pre>
            {{ sensors }}
            </pre>
    </div>
</template>

<script>
    import { mapActions, mapGetters } from 'vuex';

    export default {
        mounted() {
            this.loadById({id:'1'});
        },

        data() {
            return {
            };
        },
        methods: {
            ...mapActions({
                    loadById: 'sensors/loadById',
            }),
        },
        computed: {
            ...mapGetters({
                    sensors: 'sensors/byId',
            }),
        }
    }
</script>
```

**Comment by andreas83** [comment]
And one last question: how do i get the result.id after a dataset is created via:
```
const recordData = {
  attributes: {
    title: 'My Widget',
  },
};
this.$store.dispatch('widgets/create', recordData);
```
Sorry for abusing the issue tracker. If you do not like to answer those silly "support" questions, please simply let me know and i will stop immediately.

**Comment by CodingItWrong** [comment]
1. I think a type conversion for the ID is a good idea, I'll add that.
2. Thanks for letting me know about that typo.
3. Yup, it's the same reason here: the `byId` getter is a parameterized getter, so it's a function. You would want to pass the ID to it.

To get the widget ID after creating a record, maybe I could make a `lastCreated` getter that would return the last record created, including the ID. It would also include any other data returned from the server upon create, like if there are fields like `created_at` that the server auto-populates. Does that solution sound like it would work?

**Comment by andreas83** [comment]
Yes that's exactly what i'm looking for :+1:

**Comment by CodingItWrong** [comment]
OK, 0.0.8 is released with those changes. Here are the docs for `lastCreated`: https://vuex.reststate.org/writing-data.html#create-lastcreated

No worries on the support requests. I'm excited to have someone using the library and driving it forward to more robustness! Just be aware that it's still 0.0.x software so issues will come up, and I actually have a newborn right now so it might take me a few days to get fixes in sometimes :-)

You can close this issue once you confirm it's working ok 👍

**Comment by andreas83** [comment]
turns out i like to test other peoples software, usually its the other way around.  
congrats to your newborn :tada: hope you get enough sleep :sweat_smile: 
 i tested the lastCreated getter and it works as expected. that's very helpful right now THANK YOU :)
