### ISSUE TITLE
How to use another field as id for loadById?

### ISSUE THREAD

**Issue by mdrews21** [reststate/reststate-vuex#251]
Is there a way to use another field to retrieve a single record from vuex state? I can only use "id" field. Since I have a uuid-field i want to use this. Expected:
`this.$store.dispatch('widgets/loadById', { uuid: xyz }).then(() => {
  const widget = this.$store.getters['widgets/byId']({ uuid: xyz });
  console.log(widget);
});
`
Thank You!

**Comment by CodingItWrong** [comment]
Reststate/Vuex is limited in how it fetches data from the server by the mechanisms JSON:API provides.

If your server uses the UUID as part of the URL for a record, then `widgets/loadById` will work to load the record. But from your question I'm assuming that's not the case: you have a UUID field _separate_ from the ID.

In that case, the mechanism JSON:API provides to load records from the server based on a field is filtering. The `loadWhere` action and `where` getter will allow you to retrieve a record based on any field, including UUID. This will return an array because JSON:API and Reststate don't know that your UUID field is guaranteed to be unique; you can just access the single record in that array.
