### ISSUE TITLE
Why is state a function rather than an object?

### ISSUE THREAD

**Issue by geoidesic** [reststate/reststate-vuex#270]
The problem with having it as a function is that you can't do clever things like merge the reststate state of a store with other state that you might need to track in the same store because you end up with Webpack errors.

Why not simplify this and make it just an object? I've tested this and it works.

**Comment by CodingItWrong** [comment]
Having state a function fixes #255, a warning in Nuxt.

Also, since May of this year state as a function is the official/documented way to set up the state: https://vuex.vuejs.org/guide/modules.html#module-local-state

> you can't do clever things like merge the reststate state of a store with other state that you might need to track in the same store

I don't quite follow. If you mean you want to add additional state to the store in another module, that should work fine—modules are isolated from one another. If you mean you want to add additional state to the reststate module, I would recommend leaving the reststate module as-is and storing additional state you want in a separate module. Modules are there to be isolated from one another, so keeping them separate respects this.

**Comment by CodingItWrong** [comment]
Also, I'm surprised you asked why state is a function rather than an object; GitHub sent me an email saying that you commented on the PR where it was changed, that explained it:

<img width="593" alt="Screen Shot 2020-10-17 at 6 35 39 AM" src="https://user-images.githubusercontent.com/15832198/96335011-140a3a80-1043-11eb-985a-cc7f35391f13.png">

I don't see that comment anymore; did you delete it?

**Comment by geoidesic** [comment]
So I've been trying to solve a mysterious bug which only appears on my vue app when I build, it doesn't appear on the dev server.

This change (i.e. return as a function) causes the error I get to change. That's all I was saying. I wasn't sure exactly why, so I deleted the comment.

I do mean that I want to add additional state to the restate module. I understand module isolation but this isn't about adding unrelated state, it's about adding state that relates to that module. I don't want to go into all the details because it's complicated and you really don't need to know, but trust me when I say that I need to be able to merge additional information about that store into it's state for integration purposes.

Since you've made this change now, it completely breaks my application in a way that isn't fixable. 

I think what's clear is that the requirement to return state as a function or as an object actually varies according to the build environment. So for example Nuxt requires function, as does SSR, but my app requires it to be an object.

So maybe the only sensible way forward is to make it configurable.

**Comment by CodingItWrong** [comment]
> I think what's clear is that the requirement to return state as a function or as an object actually varies according to the build environment. So for example Nuxt requires function, as does SSR, but my app requires it to be an object.

The documented way in the Vuex documentation is for state to be a function. Nuxt is a major Vue ecosystem framework that follows the documented way to define the state. Your app is an individual app that was relying on an implementation detail of reststate that has now changed, as well as working against the spirit of how modules are supposed to work. That doesn't add up to an equally-valid need that should be supported by a configuration option.

I understand it's frustrating that an update isn't compatible with your app. I recommend locking your dependency to 0.2.2. Not much active development is happening in the library so things won't move on beyond that too quickly.

**Comment by geoidesic** [comment]
I've updated the PR with config option.

**Comment by geoidesic** [comment]
I hear you though. Makes sense. I'll consider again whether I can use separate modules instead of merging. Thanks for the feedback.
