### ISSUE TITLE
A way to fetch current user (/users/me)

### ISSUE THREAD

**Issue by orarbel** [reststate/reststate-vuex#89]
I could not find a way to fetch the current user.

I added to the api a custom hook that replaces "me" with the current user id, but then in the client I can't know what is the current id.

Is there something I'm missing?

**Comment by CodingItWrong** [comment]
This sounds like a question that's specific to your own backend setup, so I think I'd need more info to help you brainstorm a solution.

Are you saying your API has an endpoint `/users/me` and you want to hit it? Or are you saying your API has an endpoint `/users/27` for example, and you just need a way to know what the user ID of your logged-in user is?

**Comment by orarbel** [comment]
Thank you for responding. 

Let's say I just need a way to know what the user ID of your logged-in user is

**Comment by CodingItWrong** [comment]
This library doesn't have the concept of a user, so it can't tell you that. If your app has login Auth code, you would need to use that code to tell you what the user ID is. When I write apps with Reststate/Vuex I make login requests directly with Axios, then store the returned user data in local storage. So that would be one approach.

**Comment by orarbel** [comment]
Got it, thanks!
